name: eh_downloader_flutter
description: Flutter Frontend for EH Downloader
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dio: ^5.3.2
  dio_cookie_manager: ^3.1.0+1
  flutter:
    sdk: flutter
  go_router: ^10.1.0
  json_annotation: ^4.8.1
  path_provider: ^2.1.0
  retrofit: ^4.0.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
