name: eh_downloader_flutter
description: Flutter Frontend for EH Downloader
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  chinese_font_library: ^1.0.2
  cryptography: ^2.5.0
  cryptography_flutter: ^2.3.0
  dio: ^5.3.2
  dio_cookie_manager: ^3.1.0+1
  dio_image_provider: any
  enum_flag: ^1.0.2
  event_listener: ^0.2.0
  file: ^6.1.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.0
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^10.1.0
  image: ^4.0.17
  infinite_scroll_pagination: ^4.0.0
  intl: any
  json_annotation: ^4.8.1
  keymap: ^0.0.92
  logging: ^1.2.0
  palette_generator: ^0.3.3+3
  path: ^1.8.3
  path_provider: ^2.1.0
  photo_view: ^0.14.0
  retrofit: ^4.0.1
  shared_preferences: ^2.2.0
  super_clipboard: ^0.6.4
  super_context_menu: ^0.6.4
  user_agent_analyzer: ^5.0.0
  window_manager: ^0.3.6

dependency_overrides:
  cookie_jar:
    git:
      url: https://github.com/lifegpc/cookie_jar.git
      ref: main
      path: .

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true
