name: Android Build
on:
  push:
    branches: ["*"]
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4
    - name: Setup flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.SIGNING_STORE_BASE64 }}
      run: echo $ENCODED_STRING | base64 -di > android/app/keystore.jks
    - name: Build apk
      run: flutter build apk --release --split-per-abi
      env:
          CI: true
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with: 
        name: app-release
        path: build/app/outputs/flutter-apk/*
