name: Deploy
on:
  push:
    branches: [master]
concurrency:
  group: deploy
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install wrangler
        run: npm install wrangler -g
      - name: Build web
        run: flutter build web
      - name: Upload
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: wrangler pages deploy build/web --name=ehf --branch=dev
    
