name: Linux Build
on:
  push:
    branches: ["*"]
    paths-ignore:
      - '.devcontainer/**'
      - '.github/workflows/android.yml'
      - '.github/workflows/ios.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/web.yml'
      - '.github/workflows/windows.yml'
      - 'android/**'
      - 'ios/**'
      - 'macos/**'
      - 'web/**'
      - 'windows/**'
      - '.gitignore'
      - '.gitmodules'
      - 'README.md'
      - 'LICENSE'
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev liblzma-dev libstdc++-12-dev ninja-build
      - name: Build
        run: flutter build linux --release
      - name: Package files
        run: cd build/linux/x64/release/bundle && 7z a -mx9 -y ../../../../../linux.7z
      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: ./linux.7z
