name: MacOS Build
on:
  push:
    branches: ["*"]
    paths-ignore:
      - '.github/workflows/android.yml'
      - '.github/workflows/ios.yml'
      - '.github/workflows/linux.yml'
      - '.github/workflows/web.yml'
      - '.github/workflows/windows.yml'
      - 'android/**'
      - 'ios/**'
      - 'linux/**'
      - 'web/**'
      - 'windows/**'
      - '.gitignore'
      - '.gitmodules'
      - 'README.md'
      - 'LICENSE'
jobs:
  macos:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build
        run: flutter build macos --release
      - name: Archive
        run: |
          cd build/macos/Build/Products/Release
          7z a -mx9 -y macos.7z eh_downloader_flutter.app
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: build/macos/Build/Products/Release/macos.7z
