name: Web
on:
  push:
    branches: ["*"]
    paths-ignore:
     - '.github/workflows/android.yml'
     - '.github/workflows/linux.yml'
     - '.github/workflows/windows.yml'
     - 'android/**'
     - 'ios/**'
     - 'linux/**'
     - 'macos/**'
     - 'windows/**'
     - '.gitignore'
     - '.gitmodules'
     - 'README.md'
     - 'LICENSE'
concurrency:
  group: deploy
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install wrangler
        run: npm install wrangler -g
      - name: Build web
        run: flutter build web
      - name: Upload
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: wrangler pages deploy build/web --project-name=ehf --branch=dev
