name: Windows build
on:
  push:
    branches: ["*"]
    paths-ignore:
     - '.github/workflows/android.yml'
     - '.github/workflows/ios.yml'
     - '.github/workflows/linux.yml'
     - '.github/workflows/macos.yml'
     - '.github/workflows/web.yml'
     - 'android/**'
     - 'ios/**'
     - 'linux/**'
     - 'macos/**'
     - 'web/**'
     - '.gitignore'
     - '.gitmodules'
     - 'README.md'
     - 'LICENSE'
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build
        run: flutter build windows --release
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2
      - name: Build resources
        run: cd windows/resources && msbuild /p:Configuration=Release && Copy-Item "x64/Release/resources.dll" -Destination "../../build/windows/x64/runner/Release/resources.dll"
      - name: Download required dynamic library
        run: Invoke-WebRequest -OutFile build/windows/x64/runner/Release/sqlite3.dll "https://github.com/tekartik/sqflite/raw/master/sqflite_common_ffi/lib/src/windows/sqlite3.dll"
      - name: Package files
        run: cd build/windows/x64/runner/Release && 7z a -mx9 -y ../../../../../windows.7z
      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: ./windows.7z
